swagger: "2.0"
info:
  title: Cellar Service
  description: HTTP service for managing your wine cellar
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api-auction/getAuctionProductListByStatus:
    post:
      tags:
      - auction
      summary: getAuctionProductListByStatus auction
      description: 获取拍卖列表
      operationId: auction#getAuctionProductListByStatus
      parameters:
      - name: GetAuctionProductListByStatusRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AuctionGetAuctionProductListByStatusRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuctionAuctionProductResponseAuctionListCollection'
      schemes:
      - http
  /swagger/swagger.json:
    get:
      summary: Download ../../gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
  /user:
    get:
      tags:
      - user
      summary: list user
      description: List all stored bottles
      operationId: user#list
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserStoredBottleResponseTinyCollection'
      schemes:
      - http
    post:
      tags:
      - user
      summary: add user
      description: Add new bottle and return its ID.
      operationId: user#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserAddRequestBody'
          required:
          - name
          - winery
          - vintage
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /user/{id}:
    get:
      tags:
      - user
      summary: show user
      description: Show bottle by ID
      operationId: user#show
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        enum:
        - default
        - tiny
      - name: id
        in: path
        description: ID of bottle to show
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserShowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/UserShowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
    delete:
      tags:
      - user
      summary: remove user
      description: Remove bottle from storage
      operationId: user#remove
      parameters:
      - name: id
        in: path
        description: ID of bottle to remove
        required: true
        type: string
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
  /user/multi_add:
    post:
      tags:
      - user
      summary: multi_add user
      description: Add n number of bottles and return their IDs. This is a multipart
        request and each part has field name 'bottle' and contains the encoded bottle
        info to be added.
      operationId: user#multi_add
      parameters:
      - name: array
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/BottleRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Reiciendis quod consectetur quas consequatur error atque.
      schemes:
      - http
  /user/multi_update:
    put:
      tags:
      - user
      summary: multi_update user
      description: Update bottles with the given IDs. This is a multipart request
        and each part has field name 'bottle' and contains the encoded bottle info
        to be updated. The IDs in the query parameter is mapped to each part in the
        request.
      operationId: user#multi_update
      parameters:
      - name: ids
        in: query
        description: IDs of the bottles to be updated
        required: true
        type: array
        items:
          type: string
        collectionFormat: multi
      - name: multi_update_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserMultiUpdateRequestBody'
          required:
          - bottles
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
  /user/rate:
    post:
      tags:
      - user
      summary: rate user
      description: Rate bottles by IDs
      operationId: user#rate
      responses:
        "200":
          description: OK response.
      schemes:
      - http
definitions:
  AuctionAuctionProductResponseAuctionListCollection:
    title: 'Mediatype identifier: application/vnd.cellar.stored-bottle; type=collection;
      view=auctionList'
    type: array
    items:
      $ref: '#/definitions/AuctionProductResponseAuctionList'
    description: AuctionAuctionProductResponseAuctionListCollection is the result
      type for an array of AuctionProductResponseAuctionList (default view)
    example:
    - add_price: 20
      art_no: ZS1908038
      auction_status: 1
      auction_type: 2
      bid_scene_id: -1
      bond_price: 20
      buy_number: 0
      buy_unit_price: Est eum illum.
      buyout_price: 200
      cap_price: 390
      crowdfunding_package_id: Ipsa occaecati dolorum et corporis rem voluptatem.
      current_price: 110
      end_time: 1567396800000
      head_portrait: Recusandae quam qui labore animi.
      id: "50611"
      is_have_proxy: 1
      is_reserve_price: 2
      last_time: 1567396800000
      limit_number: 1
      mkt_price: 395
      pictures_url: ""
      prod_id: 21320
      prod_name: 朱砂平安扣
      qr_url: ""
      remind_time: 1567389600000
      reserve_price: Nam nemo pariatur.
      result_status: -1
      serial_num: 10:00~12:00
      share_url: Quo laudantium qui ducimus animi eos a.
      start_auction_price: 110
      start_time: 1567389600000
      title: 朱砂平安扣
      total_number: 1
      transaction_number: 0
      transaction_price: Quia omnis.
      user_id: Atque voluptatem.
      user_name: Distinctio aut non.
    - add_price: 20
      art_no: ZS1908038
      auction_status: 1
      auction_type: 2
      bid_scene_id: -1
      bond_price: 20
      buy_number: 0
      buy_unit_price: Est eum illum.
      buyout_price: 200
      cap_price: 390
      crowdfunding_package_id: Ipsa occaecati dolorum et corporis rem voluptatem.
      current_price: 110
      end_time: 1567396800000
      head_portrait: Recusandae quam qui labore animi.
      id: "50611"
      is_have_proxy: 1
      is_reserve_price: 2
      last_time: 1567396800000
      limit_number: 1
      mkt_price: 395
      pictures_url: ""
      prod_id: 21320
      prod_name: 朱砂平安扣
      qr_url: ""
      remind_time: 1567389600000
      reserve_price: Nam nemo pariatur.
      result_status: -1
      serial_num: 10:00~12:00
      share_url: Quo laudantium qui ducimus animi eos a.
      start_auction_price: 110
      start_time: 1567389600000
      title: 朱砂平安扣
      total_number: 1
      transaction_number: 0
      transaction_price: Quia omnis.
      user_id: Atque voluptatem.
      user_name: Distinctio aut non.
    - add_price: 20
      art_no: ZS1908038
      auction_status: 1
      auction_type: 2
      bid_scene_id: -1
      bond_price: 20
      buy_number: 0
      buy_unit_price: Est eum illum.
      buyout_price: 200
      cap_price: 390
      crowdfunding_package_id: Ipsa occaecati dolorum et corporis rem voluptatem.
      current_price: 110
      end_time: 1567396800000
      head_portrait: Recusandae quam qui labore animi.
      id: "50611"
      is_have_proxy: 1
      is_reserve_price: 2
      last_time: 1567396800000
      limit_number: 1
      mkt_price: 395
      pictures_url: ""
      prod_id: 21320
      prod_name: 朱砂平安扣
      qr_url: ""
      remind_time: 1567389600000
      reserve_price: Nam nemo pariatur.
      result_status: -1
      serial_num: 10:00~12:00
      share_url: Quo laudantium qui ducimus animi eos a.
      start_auction_price: 110
      start_time: 1567389600000
      title: 朱砂平安扣
      total_number: 1
      transaction_number: 0
      transaction_price: Quia omnis.
      user_id: Atque voluptatem.
      user_name: Distinctio aut non.
    - add_price: 20
      art_no: ZS1908038
      auction_status: 1
      auction_type: 2
      bid_scene_id: -1
      bond_price: 20
      buy_number: 0
      buy_unit_price: Est eum illum.
      buyout_price: 200
      cap_price: 390
      crowdfunding_package_id: Ipsa occaecati dolorum et corporis rem voluptatem.
      current_price: 110
      end_time: 1567396800000
      head_portrait: Recusandae quam qui labore animi.
      id: "50611"
      is_have_proxy: 1
      is_reserve_price: 2
      last_time: 1567396800000
      limit_number: 1
      mkt_price: 395
      pictures_url: ""
      prod_id: 21320
      prod_name: 朱砂平安扣
      qr_url: ""
      remind_time: 1567389600000
      reserve_price: Nam nemo pariatur.
      result_status: -1
      serial_num: 10:00~12:00
      share_url: Quo laudantium qui ducimus animi eos a.
      start_auction_price: 110
      start_time: 1567389600000
      title: 朱砂平安扣
      total_number: 1
      transaction_number: 0
      transaction_price: Quia omnis.
      user_id: Atque voluptatem.
      user_name: Distinctio aut non.
  AuctionGetAuctionProductListByStatusRequestBody:
    title: AuctionGetAuctionProductListByStatusRequestBody
    type: object
    properties:
      auction_status:
        type: integer
        description: 拍卖状态
        example: 2
        format: int64
      current_page:
        type: integer
        description: 当前页数
        example: 1
        format: int64
      page_size:
        type: integer
        description: 每页返回的条数
        example: 30
        format: int64
    example:
      auction_status: 2
      current_page: 1
      page_size: 30
  AuctionProductResponseAuctionList:
    title: 'Mediatype identifier: application/vnd.cellar.stored-bottle; view=default'
    type: object
    properties:
      add_price:
        type: integer
        example: 20
        format: int64
      art_no:
        type: string
        example: ZS1908038
      auction_status:
        type: integer
        example: 1
        format: int64
      auction_type:
        type: integer
        example: 2
        format: int64
      bid_scene_id:
        type: integer
        example: -1
        format: int64
      bond_price:
        type: integer
        example: 20
        format: int64
      buy_number:
        type: integer
        example: 0
        format: int64
      buy_unit_price:
        type: string
        example: Adipisci ut laboriosam porro soluta.
      buyout_price:
        type: integer
        example: 200
        format: int64
      cap_price:
        type: integer
        example: 390
        format: int64
      crowdfunding_package_id:
        type: string
        example: Ducimus et culpa et.
      current_price:
        type: integer
        example: 110
        format: int64
      end_time:
        type: integer
        example: 1567396800000
        format: int64
      head_portrait:
        type: string
        example: Eum quis dolor mollitia est.
      id:
        type: string
        example: "50611"
      is_have_proxy:
        type: integer
        example: 1
        format: int64
      is_reserve_price:
        type: integer
        example: 2
        format: int64
      last_time:
        type: integer
        example: 1567396800000
        format: int64
      limit_number:
        type: integer
        example: 1
        format: int64
      mkt_price:
        type: integer
        example: 395
        format: int64
      pictures_url:
        type: string
        example: ""
      prod_id:
        type: integer
        example: 21320
        format: int32
      prod_name:
        type: string
        example: 朱砂平安扣
      qr_url:
        type: string
        example: ""
      remind_time:
        type: integer
        example: 1567389600000
        format: int64
      reserve_price:
        type: string
        example: Rerum dignissimos est non est ipsam.
      result_status:
        type: integer
        example: -1
        format: int64
      serial_num:
        type: string
        example: 10:00~12:00
      share_url:
        type: string
        example: Hic qui iusto nobis dolores voluptate odit.
      start_auction_price:
        type: integer
        example: 110
        format: int64
      start_time:
        type: integer
        example: 1567389600000
        format: int64
      title:
        type: string
        example: 朱砂平安扣
      total_number:
        type: integer
        example: 1
        format: int64
      transaction_number:
        type: integer
        example: 0
        format: int64
      transaction_price:
        type: string
        example: Facilis sit necessitatibus.
      user_id:
        type: string
        example: Numquam dolor esse ullam nisi.
      user_name:
        type: string
        example: Architecto voluptas aut harum perferendis est.
    description: A StoredBottle describes a bottle retrieved by the storage service.
      (auctionList view) (default view)
    example:
      add_price: 20
      art_no: ZS1908038
      auction_status: 1
      auction_type: 2
      bid_scene_id: -1
      bond_price: 20
      buy_number: 0
      buy_unit_price: Libero accusantium molestiae voluptatibus quo.
      buyout_price: 200
      cap_price: 390
      crowdfunding_package_id: Quibusdam aperiam blanditiis qui id.
      current_price: 110
      end_time: 1567396800000
      head_portrait: Recusandae soluta ut.
      id: "50611"
      is_have_proxy: 1
      is_reserve_price: 2
      last_time: 1567396800000
      limit_number: 1
      mkt_price: 395
      pictures_url: ""
      prod_id: 21320
      prod_name: 朱砂平安扣
      qr_url: ""
      remind_time: 1567389600000
      reserve_price: Error accusamus.
      result_status: -1
      serial_num: 10:00~12:00
      share_url: Mollitia quam.
      start_auction_price: 110
      start_time: 1567389600000
      title: 朱砂平安扣
      total_number: 1
      transaction_number: 0
      transaction_price: Et quisquam unde similique.
      user_id: Aliquam dicta quo voluptas quod sit.
      user_name: Voluptatem accusantium.
  BottleRequestBody:
    title: BottleRequestBody
    type: object
    properties:
      composition:
        type: array
        items:
          $ref: '#/definitions/ComponentRequestBody'
        description: Composition is the list of grape varietals and associated percentage.
        example:
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
      description:
        type: string
        description: Description of bottle
        example: Red wine blend with an emphasis on the Cabernet Franc grape and including
          other Bordeaux grape varietals and some Syrah
        maxLength: 2000
      name:
        type: string
        description: Name of bottle
        example: Blue's Cuvee
        maxLength: 100
      rating:
        type: integer
        description: Rating of bottle from 1 (worst) to 5 (best)
        example: 3
        minimum: 1
        maximum: 5
      vintage:
        type: integer
        description: Vintage of bottle
        example: 2015
        minimum: 1900
        maximum: 2020
      winery:
        $ref: '#/definitions/WineryRequestBody'
    description: Bottle describes a bottle of wine to be stored.
    example:
      composition:
      - percentage: 19
        varietal: Syrah
      - percentage: 19
        varietal: Syrah
      description: Red wine blend with an emphasis on the Cabernet Franc grape and
        including other Bordeaux grape varietals and some Syrah
      name: Blue's Cuvee
      rating: 1
      vintage: 1968
      winery:
        country: USA
        name: Longoria
        region: Central Coast, California
        url: http://www.longoriawine.com/
    required:
    - name
    - winery
    - vintage
  ComponentRequestBody:
    title: ComponentRequestBody
    type: object
    properties:
      percentage:
        type: integer
        description: Percentage of varietal in wine
        example: 91
        minimum: 1
        maximum: 100
      varietal:
        type: string
        description: Grape varietal
        example: Syrah
        pattern: '[A-Za-z'' ]+'
        maxLength: 100
    example:
      percentage: 50
      varietal: Syrah
    required:
    - varietal
  ComponentResponseBody:
    title: ComponentResponseBody
    type: object
    properties:
      percentage:
        type: integer
        description: Percentage of varietal in wine
        example: 55
        minimum: 1
        maximum: 100
      varietal:
        type: string
        description: Grape varietal
        example: Syrah
        pattern: '[A-Za-z'' ]+'
        maxLength: 100
    example:
      percentage: 64
      varietal: Syrah
    required:
    - varietal
  StoredBottleResponseTiny:
    title: 'Mediatype identifier: storedbottle; view=default'
    type: object
    properties:
      id:
        type: string
        description: ID is the unique id of the bottle.
        example: 123abc
      name:
        type: string
        description: Name of bottle
        example: Blue's Cuvee
        maxLength: 100
      winery:
        $ref: '#/definitions/WineryResponseTiny'
    description: A StoredBottle describes a bottle retrieved by the storage service.
      (tiny view) (default view)
    example:
      id: 123abc
      name: Blue's Cuvee
      winery:
        name: Longoria
    required:
    - id
    - name
    - winery
  UserAddRequestBody:
    title: UserAddRequestBody
    type: object
    properties:
      composition:
        type: array
        items:
          $ref: '#/definitions/ComponentRequestBody'
        description: Composition is the list of grape varietals and associated percentage.
        example:
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
      description:
        type: string
        description: Description of bottle
        example: Red wine blend with an emphasis on the Cabernet Franc grape and including
          other Bordeaux grape varietals and some Syrah
        maxLength: 2000
      name:
        type: string
        description: Name of bottle
        example: Blue's Cuvee
        maxLength: 100
      rating:
        type: integer
        description: Rating of bottle from 1 (worst) to 5 (best)
        example: 4
        minimum: 1
        maximum: 5
      vintage:
        type: integer
        description: Vintage of bottle
        example: 1918
        minimum: 1900
        maximum: 2020
      winery:
        $ref: '#/definitions/WineryRequestBody'
    example:
      composition:
      - percentage: 19
        varietal: Syrah
      - percentage: 19
        varietal: Syrah
      - percentage: 19
        varietal: Syrah
      description: Red wine blend with an emphasis on the Cabernet Franc grape and
        including other Bordeaux grape varietals and some Syrah
      name: Blue's Cuvee
      rating: 2
      vintage: 1904
      winery:
        country: USA
        name: Longoria
        region: Central Coast, California
        url: http://www.longoriawine.com/
    required:
    - name
    - winery
    - vintage
  UserMultiUpdateRequestBody:
    title: UserMultiUpdateRequestBody
    type: object
    properties:
      bottles:
        type: array
        items:
          $ref: '#/definitions/BottleRequestBody'
        description: Array of bottle info that matches the ids attribute
        example:
        - composition:
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          description: Red wine blend with an emphasis on the Cabernet Franc grape
            and including other Bordeaux grape varietals and some Syrah
          name: Blue's Cuvee
          rating: 1
          vintage: 1957
          winery:
            country: USA
            name: Longoria
            region: Central Coast, California
            url: http://www.longoriawine.com/
        - composition:
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          description: Red wine blend with an emphasis on the Cabernet Franc grape
            and including other Bordeaux grape varietals and some Syrah
          name: Blue's Cuvee
          rating: 1
          vintage: 1957
          winery:
            country: USA
            name: Longoria
            region: Central Coast, California
            url: http://www.longoriawine.com/
        - composition:
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          description: Red wine blend with an emphasis on the Cabernet Franc grape
            and including other Bordeaux grape varietals and some Syrah
          name: Blue's Cuvee
          rating: 1
          vintage: 1957
          winery:
            country: USA
            name: Longoria
            region: Central Coast, California
            url: http://www.longoriawine.com/
        - composition:
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          - percentage: 19
            varietal: Syrah
          description: Red wine blend with an emphasis on the Cabernet Franc grape
            and including other Bordeaux grape varietals and some Syrah
          name: Blue's Cuvee
          rating: 1
          vintage: 1957
          winery:
            country: USA
            name: Longoria
            region: Central Coast, California
            url: http://www.longoriawine.com/
    example:
      bottles:
      - composition:
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        description: Red wine blend with an emphasis on the Cabernet Franc grape and
          including other Bordeaux grape varietals and some Syrah
        name: Blue's Cuvee
        rating: 1
        vintage: 1957
        winery:
          country: USA
          name: Longoria
          region: Central Coast, California
          url: http://www.longoriawine.com/
      - composition:
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        description: Red wine blend with an emphasis on the Cabernet Franc grape and
          including other Bordeaux grape varietals and some Syrah
        name: Blue's Cuvee
        rating: 1
        vintage: 1957
        winery:
          country: USA
          name: Longoria
          region: Central Coast, California
          url: http://www.longoriawine.com/
      - composition:
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        - percentage: 19
          varietal: Syrah
        description: Red wine blend with an emphasis on the Cabernet Franc grape and
          including other Bordeaux grape varietals and some Syrah
        name: Blue's Cuvee
        rating: 1
        vintage: 1957
        winery:
          country: USA
          name: Longoria
          region: Central Coast, California
          url: http://www.longoriawine.com/
    required:
    - bottles
  UserShowNotFoundResponseBody:
    title: UserShowNotFoundResponseBody
    type: object
    properties:
      id:
        type: string
        description: ID of missing bottle
        example: Hic fuga.
      message:
        type: string
        description: Message of error
        example: bottle 1 not found
    description: Bottle not found
    example:
      id: Ut labore velit laborum facilis repudiandae.
      message: bottle 1 not found
    required:
    - message
    - id
  UserShowResponseBody:
    title: 'Mediatype identifier: storedbottle; view=default'
    type: object
    properties:
      composition:
        type: array
        items:
          $ref: '#/definitions/ComponentResponseBody'
        description: Composition is the list of grape varietals and associated percentage.
        example:
        - percentage: 49
          varietal: Syrah
        - percentage: 49
          varietal: Syrah
        - percentage: 49
          varietal: Syrah
        - percentage: 49
          varietal: Syrah
      description:
        type: string
        description: Description of bottle
        example: Red wine blend with an emphasis on the Cabernet Franc grape and including
          other Bordeaux grape varietals and some Syrah
        maxLength: 2000
      id:
        type: string
        description: ID is the unique id of the bottle.
        example: 123abc
      name:
        type: string
        description: Name of bottle
        example: Blue's Cuvee
        maxLength: 100
      rating:
        type: integer
        description: Rating of bottle from 1 (worst) to 5 (best)
        example: 3
        minimum: 1
        maximum: 5
      vintage:
        type: integer
        description: Vintage of bottle
        example: 1964
        minimum: 1900
        maximum: 2020
      winery:
        $ref: '#/definitions/WineryResponseBodyTiny'
    description: ShowResponseBody result type (default view)
    example:
      composition:
      - percentage: 49
        varietal: Syrah
      - percentage: 49
        varietal: Syrah
      - percentage: 49
        varietal: Syrah
      description: Red wine blend with an emphasis on the Cabernet Franc grape and
        including other Bordeaux grape varietals and some Syrah
      id: 123abc
      name: Blue's Cuvee
      rating: 4
      vintage: 1984
      winery:
        name: Longoria
    required:
    - id
    - name
    - winery
    - vintage
  UserStoredBottleResponseTinyCollection:
    title: 'Mediatype identifier: storedbottle; type=collection; view=tiny'
    type: array
    items:
      $ref: '#/definitions/StoredBottleResponseTiny'
    description: UserStoredBottleResponseTinyCollection is the result type for an
      array of StoredBottleResponseTiny (default view)
    example:
    - id: 123abc
      name: Blue's Cuvee
      winery:
        name: Longoria
    - id: 123abc
      name: Blue's Cuvee
      winery:
        name: Longoria
    - id: 123abc
      name: Blue's Cuvee
      winery:
        name: Longoria
    - id: 123abc
      name: Blue's Cuvee
      winery:
        name: Longoria
  WineryRequestBody:
    title: 'Mediatype identifier: winery; view=default'
    type: object
    properties:
      country:
        type: string
        description: Country of winery
        example: USA
        pattern: (?i)[a-z '\.]+
      name:
        type: string
        description: Name of winery
        example: Longoria
      region:
        type: string
        description: Region of winery
        example: Central Coast, California
        pattern: (?i)[a-z '\.]+
      url:
        type: string
        description: Winery website URL
        example: http://www.longoriawine.com/
        pattern: (?i)^(https?|ftp)://[^\s/$.?#].[^\s]*$
    description: WineryRequestBody result type (default view)
    example:
      country: USA
      name: Longoria
      region: Central Coast, California
      url: http://www.longoriawine.com/
    required:
    - name
    - region
    - country
  WineryResponseBodyTiny:
    title: 'Mediatype identifier: winery; view=default'
    type: object
    properties:
      name:
        type: string
        description: Name of winery
        example: Longoria
    description: WineryResponseBodyTiny result type (default view)
    example:
      name: Longoria
    required:
    - name
  WineryResponseTiny:
    title: 'Mediatype identifier: winery; view=default'
    type: object
    properties:
      name:
        type: string
        description: Name of winery
        example: Longoria
    description: WineryResponseTiny result type (default view)
    example:
      name: Longoria
    required:
    - name
